### ISSUE TITLE
석미혜 1주차 인증

### ISSUE THREAD

**Issue by mmihye** [PinaryStudy/Git-Task#13]
### 💡 깃의 3가지 영역
**Working Dir** : 변경 사항 발생
    - 파일 추가 or 삭제
    - 파일 변경(내용 추가 or 삭제 )
    - 파일 경로 변경 등

add 명령어 (snapshot 기록) 
-> **Staging Area**

commit 명령어 (변경사항 저장)
 -> **Local Repo**
<br>

### 💡 깃의 4가지 상태
- **Untracked 상태**: git이 추적하지 않는 상태
- **Tracked 상태** : git이 파일의 변경사항을 추적중인 상태
    - **Unmodified** : commit으로 저장되었고, 더 이상 변경이 없는 상태
    - **Modified** : commit 한 저장 내용에서 추가적으로 변경이 발생한 상태
    - **Staged** : add하여 Staging Area에 기록된 상태
<br>

### 💡 자신만의 정리
- `git status`
: git에 대한 상태 보기
- `git init`
: 비어있는 git 레포지토리 생성 
- `git add (추가하고자하는 파일 이름)`
: 파일이 Staging Area에 snapshot으로 기록
- `git commit -m "커밋메시지"`(Unmodified 상태)
: 변경사항 저장
- `git log`
: git에서 커밋에 대한 Log 확인
<img width="399" alt="스크린샷 2023-10-27 오전 11 48 08" src="https://github.com/PinaryStudy/Git-Task/assets/92644651/783164e5-07a0-4e0f-97a1-896a0fb3785f">

<br><br>

**작성자: **
석미혜
<br>

@jinsu4755

**Comment by jinsu4755** [comment]
고생하셨습니다
