### ISSUE TITLE
이성민 1주차 인증

### ISSUE THREAD

**Issue by seongmin221** [PinaryStudy/Git-Task#18]
### 깃의 3가지 영역

[깃의 영역]
- `Working Directory`: 작업하는 폴더, 변경사항이 있으면 탐지해서 알려줌
- `Staging Area`: add 명령어를 통한 변경사항이 기록되는 공간, index 라고도 부름
- `Local Repository`: commit 으로 저장하면 이 공간에 저장사항이 올라감, .git 디렉토리라고도  부름

<br>

[깃허브의 영역]
- `Remote Repository`: push 로 remote 의 이 공간에 저장사항이 올라감

### 깃의 4가지 상태

크게는 두 가지 상태 -> `Untracked`, `Tracked`

- `Untracked`: 깃이 추적하고 있지 않은 상태, 처음 파일이 추가된 경우
- `Tracked - Unmodified`: 커밋으로 저장되었고, 더 이상 변경사항이 없는 상태
- `Tracked - Modified`: 커밋으로 저장한 내용에 추가 변경사항이 발생한 상태
- `Tracked - Staged`: Staging area 에 기록된 상태

### 자신만의 정리

<img width="642" alt="image" src="https://github.com/PinaryStudy/Git-Task/assets/72431640/95036f8f-89ed-4c71-b8f7-08400ca7a3a7">
**작성자: 이성민**

@jinsu4755

**Comment by jinsu4755** [comment]
고생하셨습니다
